### ISSUE TITLE
Correct answer unavailable for Numpy Operations section

### ISSUE THREAD

**Issue by kevinfreeman1101** [ine-rmotr-curriculum/freecodecamp-intro-to-numpy#7]
The question for [numpy operations](https://www.freecodecamp.org/learn/data-analysis-with-python/data-analysis-with-python-course/numpy-operations) requires [0, 1, 2, 3, 4] as the answer, which is incorrect. a + 20 produces [20, 21, 22, 23, 24].

Possible Solutions:
    1. Modify the first available answer from [20, 21, 22, 24, 24] to [20, 21, 22, 23, 24]
    2. Add an additional option with the correct answer.

**Comment by kushaangowda** [comment]
In this question, they are asking for the value of 'a' after running the following code:

a = np.arange(5)
a+20

I think the correct answer is [0, 1, 2, 3, 4], as a+20 doesn't assign [20, 21, 22, 23, 24] to a.
If instead, the question was:

a = np.arange(5)
a = a+20

Then, the answer would be [20, 21, 22, 23, 24]
